### ISSUE TITLE
I cannot edit a mesh part

### ISSUE THREAD

**Issue by as3942154** [Name-hw/MeshCreator#1]
I can't edit even a ball mesh part Here is prove
![Screenshot 2024-07-03 191345](https://github.com/Name-hw/MeshCreator/assets/125905878/dcb1c4c6-9d45-4fba-8c7e-7c62d616da8f)

**Comment by as3942154** [comment]
Please reply fast.

**Comment by Name-hw** [comment]
I apologize for not replying sooner.
If you see any errors in the output, I'd appreciate it if you could send it along.
